framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    auto_setup: false
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    queues:
                        failed:
                            binding_keys: ['#']

        default_bus: messenger.bus.command

        buses:
            messenger.bus.command:
                default_middleware: false
                middleware:
                    - handle_message
