framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            events:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        type: topic
                        name: events
                    queues:
                        events:
                            binding_keys: ['#']
                retry_strategy:
                    delay: 2000
                    max_retries: 3
                    multiplier: 2
                    max_delay: 0
            failed:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    queues:
                        failed:
                            binding_keys: ['#']

        default_bus: messenger.bus.command

        buses:
            messenger.bus.command:
                default_middleware: false
                middleware:
                    - handle_message

            messenger.bus.event.async:
                default_middleware: allow_no_handlers

        routing:
            'Broadway\Domain\DomainMessage': events
