# Development environment override
services:
  php:
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./:/app
      - ./etc/frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./etc/frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      #- /app/vendor
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true

  php-worker:
    profiles:
      - donotstart

  php-worker-events:
    extends:
      file: compose.yaml
      service: php-worker
    image: ${IMAGES_PREFIX:-}app-php-worker-events
    build:
      context: .
      target: frankenphp_dev
    command: ['/app/bin/console', 'messenger:consume', 'events', '-vvv', '--time-limit=60', '--limit=10', '--memory-limit=128M']
    volumes:
      - ./:/app
      - /app/var/
    depends_on:
      php:
        condition: service_healthy

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
    volumes:
      # - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - ./var/docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

  database_management:
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    # environment:
    #   PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    volumes:
      - database_management:/var/lib/pgadmin:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # It might not work if `pgadmin` user with `uid=5050` which is used in contaner can't write in that directory on host file system.
      # - ./var/docker/db_mng:/var/lib/pgadmin:rw
      - ./etc/dev/pgadmin/config_local.py:/pgadmin4/config_local.py:ro
      - ./etc/dev/pgadmin/pgpass:/pgadmin4/pgpass:ro
      - ./etc/dev/pgadmin/servers.json:/pgadmin4/servers.json:ro
    entrypoint: >
      /bin/sh -c "
      cp -f /pgadmin4/pgpass /var/lib/pgadmin/;
      chmod 600 /var/lib/pgadmin/pgpass;
      chown pgadmin:root /var/lib/pgadmin/pgpass;
      /entrypoint.sh
      "

  amqp:
    ports:
      - "5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "${MAILPIT_PORT:-8025}:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
