apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dolphin.fullname" . }}-workers
  labels:
    {{- include "dolphin.labels" . | nindent 4 }}-workers
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dolphin.selectorLabels" . | nindent 6 }}-workers
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "dolphin.selectorLabels" . | nindent 8 }}-workers
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dolphin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-php-worker-events
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.php.image.pullPolicy }}
          command: ['bin/console', 'messenger:consume', 'events', '-vvv', '--time-limit=60', '--limit=10', '--memory-limit=128M']
          env:
            - name: RUN_MIGRATIONS
              value: "false"
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dolphin.fullname" . }}
                  key: php-app-env
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dolphin.fullname" . }}
                  key: php-app-debug
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "dolphin.fullname" . }}
                  key: php-app-secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "dolphin.fullname" . }}
                  key: database-url
            - name: MESSENGER_TRANSPORT_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "dolphin.fullname" . }}
                  key: messenger-transport-dsn
            - name: MAILER_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "dolphin.fullname" . }}
                  key: mailer-dsn
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "/bin/sleep 1; kill -QUIT 1"]
          readinessProbe:
            exec:
              command:
              - 'true'
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            exec:
              command:
              - 'true'
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
