apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dolphin.fullname" . }}
  labels:
    {{- include "dolphin.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  database-url: {{ printf "pgsql://%s:%s@%s-postgresql/%s?serverVersion=16&charset=utf8" .Values.postgresql.global.postgresql.auth.username .Values.postgresql.global.postgresql.auth.password .Release.Name .Values.postgresql.global.postgresql.auth.database | b64enc | quote }}
  {{- else }}
  database-url: {{ .Values.postgresql.url | b64enc | quote }}
  {{- end }}
  {{- if .Values.rabbitmq.enabled }}
  messenger-transport-dsn: {{ printf "amqp://%s:%s@%s-rabbitmq/%%2f/messages" .Values.rabbitmq.auth.username .Values.rabbitmq.auth.password .Release.Name | b64enc | quote }}
  {{- else }}
  messenger-transport-dsn: {{ .Values.rabbitmq.url | b64enc | quote }}
  {{- end }}
  {{- if .Values.mailpit.enabled }}
  mailer-dsn: {{ printf "smtp://%s-mailpit-smtp:%d" .Release.Name (.Values.mailpit.service.smtp.port | int) | b64enc | quote }}
  {{- else }}
  mailer-dsn: {{ .Values.mailer | b64enc | quote }}
  {{- end }}
  php-app-secret: {{ .Values.php.appSecret | default (randAlphaNum 40) | b64enc | quote }}
  mercure-jwt-secret: {{ .Values.mercure.jwtSecret | default (randAlphaNum 40) | b64enc | quote }}
